config/routes.rb
TheSystem::Application.routes.draw do
  
  resources :race_winners
  resources :race_entries

  match '/javier_castellano', to: 'jockies#javier_castellano', via: 'get'
  match '/jose_l_ortiz', to: 'jockies#jose_l_ortiz', via: 'get'
  match '/john_r_velazquez', to: 'jockies#john_r_velazquez', via: 'get'
  match '/jose_lezcano', to: 'jockies#jose_lezcano', via: 'get'
  match '/joel_rosario', to: 'jockies#joel_rosario', via: 'get'
  match '/lanfranco_dettori', to: 'jockies#lanfranco_dettori', via: 'get'
  match '/irad_ortiz_jr', to: 'jockies#irad_ortiz_jr', via: 'get'
  match '/luis_saez', to: 'jockies#luis_saez', via: 'get'
  match '/rajiv_maragh', to: 'jockies#rajiv_maragh', via: 'get'
  match '/junior_alvarado', to: 'jockies#junior_alvarado', via: 'get'

  root 'race_entries#index'

end

app/models/race_winner.rb
class RaceWinner < ActiveRecord::Base
	has_many :race_entries
end

app/controllers/race_winners_controller.rb
class RaceWinnersController < ApplicationController
  before_action :set_race_winner, only: [:show, :edit, :update, :destroy]

  # GET /race_winners
  # GET /race_winners.json
  def index
    @race_winners = RaceWinner.all.order(date: :asc, race_number: :asc).sort { |a,b| a <=> b }
  end

  # GET /race_winners/1
  # GET /race_winners/1.json
  def show
  end

  # GET /race_winners/new
  def new
    @race_winner = RaceWinner.new
  end

  # GET /race_winners/1/edit
  def edit
  end

  # POST /race_winners
  # POST /race_winners.json
  def create
    @race_winner = RaceWinner.new(race_winner_params)

    respond_to do |format|
      if @race_winner.save
        format.html { redirect_to @race_winner, notice: 'Race winner was successfully created.' }
        format.json { render action: 'show', status: :created, location: @race_winner }
      else
        format.html { render action: 'new' }
        format.json { render json: @race_winner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /race_winners/1
  # PATCH/PUT /race_winners/1.json
  def update
    respond_to do |format|
      if @race_winner.update(race_winner_params)
        format.html { redirect_to @race_winner, notice: 'Race winner was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @race_winner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /race_winners/1
  # DELETE /race_winners/1.json
  def destroy
    @race_winner.destroy
    respond_to do |format|
      format.html { redirect_to race_winners_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_race_winner
      @race_winner = RaceWinner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def race_winner_params
      params.require(:race_winner).permit(:date, :race_number, :winner, :payout)
    end
end

app/helpers/race_winners_helper.rb
module RaceWinnersHelper
end

app/views/race_winners/_form.html.erb
<%= form_for(@race_winner) do |f| %>
  <% if @race_winner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@race_winner.errors.count, "error") %> prohibited this race_winner from being saved:</h2>

      <ul>
      <% @race_winner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :race_number %><br>
    <%= f.text_field :race_number %>
  </div>
  <div class="field">
    <%= f.label :winner %><br>
    <%= f.text_field :winner %>
  </div>
  <div class="field">
    <%= f.label :payout %><br>
    <%= f.text_field :payout %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/race_winners/edit.html.erb
<h1>Editing race_winner</h1>

<%= render 'form' %>

<%= link_to 'Show', @race_winner %> |
<%= link_to 'Back', race_winners_path %>

app/views/race_winners/index.html.erb
<h1>Listing race_winners</h1>

<table id="winners" class="table table-striped">
  <thead>
    <tr>
      <th>Date</th>
      <th>Race number</th>
      <th>Winner</th>
      <th>Payout</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @race_winners.each do |race_winner| %>
      <tr>
        <td><%= race_winner.date %></td>
        <td><%= race_winner.race_number %></td>
        <td><%= race_winner.winner %></td>
        <td><%= race_winner.payout %></td>
        <td><%= link_to 'Show', race_winner %></td>
        <td><%= link_to 'Edit', edit_race_winner_path(race_winner) %></td>
        <td><%= link_to 'Destroy', race_winner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Race winner', new_race_winner_path %>

app/views/race_winners/new.html.erb
<h1>New race_winner</h1>

<%= render 'form' %>

<%= link_to 'Back', race_winners_path %>

app/views/race_winners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @race_winner.date %>
</p>

<p>
  <strong>Race number:</strong>
  <%= @race_winner.race_number %>
</p>

<p>
  <strong>Winner:</strong>
  <%= @race_winner.winner %>
</p>

<p>
  <strong>Payout:</strong>
  <%= @race_winner.payout %>
</p>

<%= link_to 'Edit', edit_race_winner_path(@race_winner) %> |
<%= link_to 'Back', race_winners_path %>