config/routes.rb
TheSystem::Application.routes.draw do
  
  resources :race_winners
  resources :race_entries

  match '/javier_castellano', to: 'jockies#javier_castellano', via: 'get'
  match '/jose_l_ortiz', to: 'jockies#jose_l_ortiz', via: 'get'
  match '/john_r_velazquez', to: 'jockies#john_r_velazquez', via: 'get'
  match '/jose_lezcano', to: 'jockies#jose_lezcano', via: 'get'
  match '/joel_rosario', to: 'jockies#joel_rosario', via: 'get'
  match '/lanfranco_dettori', to: 'jockies#lanfranco_dettori', via: 'get'
  match '/irad_ortiz_jr', to: 'jockies#irad_ortiz_jr', via: 'get'
  match '/luis_saez', to: 'jockies#luis_saez', via: 'get'
  match '/rajiv_maragh', to: 'jockies#rajiv_maragh', via: 'get'
  match '/junior_alvarado', to: 'jockies#junior_alvarado', via: 'get'

  root 'race_entries#index'

end

app/models/race_entry.rb
class RaceEntry < ActiveRecord::Base
	belongs_to :race_winner
end

app/controllers/race_entries_controller.rb
class RaceEntriesController < ApplicationController
  before_action :set_race_entry, only: [:show, :edit, :update, :destroy]

  # GET /race_entries
  # GET /race_entries.json
  def index
    @race_entries = RaceEntry.all.order(date: :asc, race: :asc).sort { |a,b| a <=> b }
  end

  # GET /race_entries/1
  # GET /race_entries/1.json
  def show
  end

  # GET /race_entries/new
  def new
    @race_entry = RaceEntry.new
  end

  # GET /race_entries/1/edit
  def edit
  end

  # POST /race_entries
  # POST /race_entries.json
  def create
    @race_entry = RaceEntry.new(race_entry_params)

    respond_to do |format|
      if @race_entry.save
        format.html { redirect_to @race_entry, notice: 'Race entry was successfully created.' }
        format.json { render action: 'show', status: :created, location: @race_entry }
      else
        format.html { render action: 'new' }
        format.json { render json: @race_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /race_entries/1
  # PATCH/PUT /race_entries/1.json
  def update
    respond_to do |format|
      if @race_entry.update(race_entry_params)
        format.html { redirect_to @race_entry, notice: 'Race entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @race_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /race_entries/1
  # DELETE /race_entries/1.json
  def destroy
    @race_entry.destroy
    respond_to do |format|
      format.html { redirect_to race_entries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_race_entry
      @race_entry = RaceEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def race_entry_params
      params.require(:race_entry).permit(:date, :race, :jockey)
    end
end

app/helpers/race_entries_helper.rb
module RaceEntriesHelper
end

app/views/race_entries/_form.html.erb
<%= form_for(@race_entry) do |f| %>
  <% if @race_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@race_entry.errors.count, "error") %> prohibited this race_entry from being saved:</h2>

      <ul>
      <% @race_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :race %><br>
    <%= f.text_field :race %>
  </div>
  <div class="field">
    <%= f.label :jockey %><br>
    <%= f.text_field :jockey %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/race_entries/edit.html.erb
<h1>Editing race_entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @race_entry %> |
<%= link_to 'Back', race_entries_path %>

app/views/race_entries/index.html.erb
<h1>Listing race_entries</h1>

<table id="entries" class="table table-striped">
  <thead>
    <tr>
      <th>Date</th>
      <th>Race</th>
      <th>Jockey</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @race_entries.each do |race_entry| %>
      <tr>
        <td><%= race_entry.date %></td>
        <td><%= race_entry.race %></td>
        <td><%= race_entry.jockey %></td>
        <td><%= link_to 'Show', race_entry %></td>
        <td><%= link_to 'Edit', edit_race_entry_path(race_entry) %></td>
        <td><%= link_to 'Destroy', race_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Race entry', new_race_entry_path %>

app/views/race_entries/new.html.erb
<h1>New race_entry</h1>

<%= render 'form' %>

<%= link_to 'Back', race_entries_path %>

app/views/race_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @race_entry.date %>
</p>

<p>
  <strong>Race:</strong>
  <%= @race_entry.race %>
</p>

<p>
  <strong>Jockey:</strong>
  <%= @race_entry.jockey %>
</p>

<%= link_to 'Edit', edit_race_entry_path(@race_entry) %> |
<%= link_to 'Back', race_entries_path %>