config/routes.rb
TheSystem::Application.routes.draw do
  
  resources :race_winners
  resources :race_entries

  match '/javier_castellano', to: 'jockies#javier_castellano', via: 'get'
  match '/jose_l_ortiz', to: 'jockies#jose_l_ortiz', via: 'get'
  match '/john_r_velazquez', to: 'jockies#john_r_velazquez', via: 'get'
  match '/jose_lezcano', to: 'jockies#jose_lezcano', via: 'get'
  match '/joel_rosario', to: 'jockies#joel_rosario', via: 'get'
  match '/lanfranco_dettori', to: 'jockies#lanfranco_dettori', via: 'get'
  match '/irad_ortiz_jr', to: 'jockies#irad_ortiz_jr', via: 'get'
  match '/luis_saez', to: 'jockies#luis_saez', via: 'get'
  match '/rajiv_maragh', to: 'jockies#rajiv_maragh', via: 'get'
  match '/junior_alvarado', to: 'jockies#junior_alvarado', via: 'get'

  root 'race_entries#index'

end

app/views/layouts/_header.html.erb
<header role="banner">
	<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
	<div class="container">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#main-navbar">
				<span class="sr-only">Toggle Navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to "TheSystem", root_path, id: "logo", class: "navbar-brand" %>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div id="main-navbar" class="collapse navbar-collapse">
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home", root_path, class: "active" %></li>
				<li><%= link_to "Race Entries", race_entries_path %></li>
				<li><%= link_to "Race Winners", race_winners_path %></li>
        <li class="dropdown">
        	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Jockies <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Javier Castellano", javier_castellano_path %></li>
            <li><%= link_to "John R. Velazquez", john_r_velazquez_path %></li>
            <li><%= link_to "Jose L. Ortiz", jose_l_ortiz_path %></li> 
            <li><%= link_to "Jose Lezcano", jose_lezcano_path %></li>
            <li><%= link_to "Joel Rosario", joel_rosario_path %></li>
            <li><%= link_to "Lanfranco Dettori", lanfranco_dettori_path %></li>
            <li><%= link_to "Irad Ortiz, Jr.", irad_ortiz_jr_path %></li>
            <li><%= link_to "Luis Saez", luis_saez_path %></li>
            <li><%= link_to "Ragiv Maragh", rajiv_maragh_path %></li>
            <li><%= link_to "Junior Alvarado", junior_alvarado_path %></li>
          </ul>
        </li>
			</ul>
		</div>
	</div>
	</nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  	<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
  	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
 		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  	<%= csrf_meta_tags %>
 	 	<%= render 'layouts/shim' %>
 	 	<meta name="viewport" content="width=device-width, initial-scale=1">
 	 	<meta name="keywords" content="<%= yield(:keywords) %>">
 	 	<meta name="description" content="<%= yield(:description) %>">
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
			<%= yield %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>